subgraph Autenticacion
    direction TB
    Login["Inicio de Sesión (RF-01, RF-08)"]
    Registro["Registro Usuarios (RF-04)"]
    Recuperacion["Recuperar Contraseña (RF-02)"]
    Verificacion["Verificación Email (RF-03)"]
    Perfil["Perfil Usuario (RF-05, RF-06)"]
  end

