graph TD
  %% Estructura Principal Vertical
  Inicio --> Autenticacion
  Autenticacion --> Contenido_Publico
  Contenido_Publico --> Interaccion_Ciudadana
  Interaccion_Ciudadana --> Gestion_Administrativa
  Gestion_Administrativa --> Infraestructura_Tecnica
